name: Intensive Weekly Tests

on:
  schedule:
    # Runs every Monday at 12:00 UTC
    - cron: '0 12 * * 1'
  workflow_dispatch:

jobs:
  tests-package:
    runs-on: ${{ matrix.os }}
    name: unit+integration tests / ${{ matrix.os }} / Python ${{ matrix.python-version }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, macos-26] # GROMACS has an issue with Ubuntu 26.04, so we wait for now
        python-version: ["3.10", "3.13"]
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v7
      with:
        fetch-depth: 0

    - name: Install GROMACS (Ubuntu)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y gromacs

    - name: Install GROMACS (macOS)
      if: runner.os == 'macOS'
      run: brew install gromacs

    - name: setup Python
      uses: actions/setup-python@v7
      with:
        python-version: ${{ matrix.python-version }}
        check-latest: true

    - run: python -m pip install tox coverage[toml]

    - name: run package tests
      run: tox -e tests-package

  tests-unit-windows:
    runs-on: ${{ matrix.os }}
    name: unit tests / ${{ matrix.os }} / Python ${{ matrix.python-version }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2025]
        python-version: ["3.10", "3.13"]
    steps:
    - uses: actions/checkout@v7
      with:
        fetch-depth: 0

    - name: setup Python
      uses: actions/setup-python@v7
      with:
        python-version: ${{ matrix.python-version }}
        check-latest: true

    - run: python -m pip install tox coverage[toml]

    - name: run unit tests
      run: tox -e tests-min

  tests-develop:
    runs-on: ${{ matrix.os }}
    name: develop tests / ${{ matrix.os }} / Python ${{ matrix.python-version }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-26.04]
        python-version: ["3.10", "3.13"]
    steps:
    - uses: actions/checkout@v7
      with:
        fetch-depth: 0

    - name: setup Python
      uses: actions/setup-python@v7
      with:
        python-version: ${{ matrix.python-version }}
        check-latest: true

    - run: python -m pip install tox

    - name: run develop (out-of-package) tests
      run: |
        tox -e tests-develop
